######################################################################
# Automatically generated by qmake (3.0) Wed Jun 13 17:18:26 2018
######################################################################

CONFIG += C++11

TEMPLATE = app
TARGET = Manifold-Cam-master

INCLUDEPATH += \
/usr/local/include/opencv\
/usr/local/include/opencv2

# Input
HEADERS += \
    djicam.h\
    tracking_utility.hpp\
    /home/ubuntu/Documents/Manifold-Cam-master/src/kcftracker.hpp\
    /home/ubuntu/Documents/Manifold-Cam-master/src/tracker.h\
    /home/ubuntu/Documents/Manifold-Cam-master/src/ffttools.hpp\
    /home/ubuntu/Documents/Manifold-Cam-master/src/fhog.hpp\
    /home/ubuntu/Documents/Manifold-Cam-master/src/labdata.hpp\
    /home/ubuntu/Documents/Manifold-Cam-master/src/recttools.hpp

SOURCES += test.cpp\
    tracking_utility.cpp\
    /home/ubuntu/Documents/Manifold-Cam-master/src/kcftracker.cpp\
    /home/ubuntu/Documents/Manifold-Cam-master/src/fhog.cpp

LIBS += -ldcam\
-lopencv_core\
-lopencv_imgproc\
-lopencv_highgui\
-lopencv_ml\
-lopencv_video\
-lopencv_features2d\
-lopencv_calib3d\
-lopencv_objdetect\
-lopencv_flann\
-lopencv_imgcodecs

